### ISSUE TITLE
Devices often go offline

### ISSUE THREAD

**Issue by sakirsek** [CoolKit-Technologies/ha-addon#108]
Devices often go offline in home assistant.  I can't send commands in home assistant when offline. It fixes itself when I press the sync button for a while.

There is no problem in the ewelink application. So I don't think there is a problem with devices and network. There seems to be a problem with home assistant's ewelink addon.

![screen1](https://user-images.githubusercontent.com/26142915/198866198-2b46a768-05c2-4c37-bcdb-3ef742e8798f.jpg)

When I check the log of the home assistant's ewelink addon, I often see the following errors:

```
[ERROR] getDataSync: diy.json ->  no data
[ERROR] getDataSync: disabled.json -> xxxxxxxxxx no data
```

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend 20221010.0 - latest

**Comment by sakirsek** [comment]
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend 20221010.0 - latest

**Comment by niezw** [comment]
Please confirm that you have updated to the latest version? 
You can post more logs to facilitate us to locate the problem. If you are worried about privacy, you can send it directly to my email gavin.nie@coolkit.cn. 
We very much hope that we can help you solve the problem.
