### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by nelsonamen** [CoolKit-Technologies/ha-addon#12]
Icons dont work on entities
![Screenshot_2021-06-26-09-33-53-171_io homeassistant companion android](https://user-images.githubusercontent.com/5807434/123507504-b57d6d80-d661-11eb-9d1f-2261fc219599.jpg)

**Comment by nelsonamen** [comment]
And the sensor door/window WiFi show as a lock can Change the name and class
![Screenshot_2021-06-26-09-44-48-564_io homeassistant companion android](https://user-images.githubusercontent.com/5807434/123507766-2e30f980-d663-11eb-8c04-0f87afa9b0e1.jpg)

**Comment by ZJia1231** [comment]
Do you mean that you want to change the icon and device name ?

**Comment by nelsonamen** [comment]
Yes

**Comment by ZJia1231** [comment]
> Yes

you can change the device name in the eWeLink WebUI, but the icon changed is not supported.
