### ISSUE TITLE
添加开关后无法在概览中控制

### ISSUE THREAD

**Issue by HotAntOne** [CoolKit-Technologies/ha-addon#123]
安装插件并登录同步后，可以正常在插件中控制开关通断。概览中可以正确显示开关状态，但是进行开关控制时显示：“调用服务 switch/turn_on 失败。Service not found”，并且开关毫无反应。

购买的设备为：Smart switch SS款 WiFi通断器

**Comment by niezw** [comment]
参考这儿的做法试试： https://github.com/CoolKit-Technologies/ha-addon/tree/master/eWeLink_Smart_Home
