### ISSUE TITLE
Cant Login to eWeLink via HA Add-On

### ISSUE THREAD

**Issue by cladkins** [CoolKit-Technologies/ha-addon#133]
The Add-On has been installed just fine and is up and running, but when I open the Web UI through HA it asks to login to ewelink with a Phone Number and Password. I can't create an account using my phone number and there is no way to add my phone number to my eWeLink account????????

**Comment by cladkins** [comment]
Sometimes I'm not smart.

**Comment by gits68** [comment]
same here, also, can't login w/ the email account created using the app
