### ISSUE TITLE
TX3EU no control over channel 1

### ISSUE THREAD

**Issue by bacharliran** [CoolKit-Technologies/ha-addon#15]
Channels 2 and 3 work as expected

**Comment by ZJia1231** [comment]
In the HA or in the eWeLink Web UI ?
Can you control the Channel1 by App?
Please specify your question.

**Comment by bacharliran** [comment]
Can't turn off channel 1 from the web ui, turning on works. Display always shows the switch is off.
I can turn on and off channel 1 by creating an automation.

**Comment by ZJia1231** [comment]
OK. We will look in to it.

**Comment by TTLucian** [comment]
Same thing happens with 4CHPROR3. Only channels 2, 3, 4, are working.
