### ISSUE TITLE
DW2-WiFi sensors not updating

### ISSUE THREAD

**Issue by TTLucian** [CoolKit-Technologies/ha-addon#18]
DW2-WiFi sensors are not updating their state in HA addon. They work fine in android app (cloud).

**Comment by TTLucian** [comment]
Nevermind. A restart of the addon fixed it!

**Comment by TTLucian** [comment]
This is still a problem. Sensors are not updating their state. They work fine in ewelink app but not in addon.

**Comment by TTLucian** [comment]
This is still a problem. DW2 WiFi sensors are not always updating their state. They work fine in ewelink app but not in addon.

**Comment by coolkit-tony** [comment]
Could you please provide the deviceid of your DW2 WiFi sensor?

**Comment by TTLucian** [comment]
1000f1652e
1000f1668a
1000f168bc
1000f16272
1000f163f6

They've been working ok for sometime now but sometimes one of them (random) gets stuck and does not report state changes anymore in the HA addon. Android app works fine.
