### ISSUE TITLE
No source?

### ISSUE THREAD

**Issue by OmgImAlexis** [CoolKit-Technologies/ha-addon#2]
You mentioned this was open source and the “source” was on GitHub. All I can see are built files in the dist directory here. Can you please add the actual source.

**Comment by ZJia1231** [comment]
This is a beta version, the source code will be release in the official version.

**Comment by OmgImAlexis** [comment]
> This is a beta version, the source code will be release in the official version.

That’s not what you said. Make the source available. Otherwise give an actual reason. If you want developers to use your code you need to be more open with it.

**Comment by niezw** [comment]
The reason is this is a beta version.We will put source code here when we release the official V1.0 version.
This is to enable HA users to experience eWeLink services earlier. 
The master branch will be the installation address for ha-addon. After the v1.0 release, the source code will be push to other branches.



> > This is a beta version, the source code will be release in the official version.
> 
> That’s not what you said. Make the source available. Otherwise give an actual reason. If you want developers to use your code you need to be more open with it.

**Comment by OmgImAlexis** [comment]
> The reason is this is a beta version.We will put source code here when we release the official V1.0 version.
> This is to enable HA users to experience eWeLink services earlier.
> The master branch will be the installation address for ha-addon. After the v1.0 release, the source code will be push to other branches.
> 
> > > This is a beta version, the source code will be release in the official version.
> > 
> > 
> > That’s not what you said. Make the source available. Otherwise give an actual reason. If you want developers to use your code you need to be more open with it.

That makes no sense. This is JavaScript we’re talking about. It’s not like keeping the source private is going to hide anything as the code isn’t even minified. Just release it.

**Comment by niezw** [comment]
Has been push
