### ISSUE TITLE
TH16R2 inconsistent behaviour

### ISSUE THREAD

**Issue by TTLucian** [CoolKit-Technologies/ha-addon#20]
Goes from "online" to "not supported":
![1](https://user-images.githubusercontent.com/1855276/127645852-53112c1e-76e7-423c-a49d-402d2c15c091.jpg)
![2](https://user-images.githubusercontent.com/1855276/127645912-627a2faf-4f18-43f2-84a8-39be7142e45a.jpg)
Works fine in android app and eWeLink web

**Comment by ZJia1231** [comment]
How did it happened ?

**Comment by TTLucian** [comment]
I've just turned on the switch. Sometime it works, sometime I get "Device is not supported". Not sure why.

**Comment by TTLucian** [comment]
This is not fixed. Still same behaviour with TH16R2. Shows online at addon startup then , after a while or after switch on shows "Device is not supported".
