### ISSUE TITLE
When restart HA custom RAW edit on lovelace will lost

### ISSUE THREAD

**Issue by zold** [CoolKit-Technologies/ha-addon#27]
When restart HA, the custom RAW edit on lovelace will lost such as  "background: var(--background-image)"
![image](https://user-images.githubusercontent.com/5059345/131440322-70c13afd-40f6-4b39-a15a-1e1f1048301d.png)
but after I remove this add-on, this issue didn't happen.

**Comment by ZJia1231** [comment]
OK, we will fix it.
