### ISSUE TITLE
Sonoff S31 - saying device not supported?

### ISSUE THREAD

**Issue by chado99** [CoolKit-Technologies/ha-addon#31]
Hi I have 2 brand new Sonoff S31 smart outlets running latest firmware. However, after I follow [official instructions ](https://sonoff.tech/product-review/tutorial/how-to-add-your-sonoff-devices-on-home-assistant/)it is says the "Devices are not supported currently". Will the S31 not work with this add-on or is something wrong?

![image](https://user-images.githubusercontent.com/17997784/134845728-aafcf37e-1cdc-40ea-a3b5-c39a209be6f3.png)

**Comment by coolkit-tony** [comment]
Hi, Sonoff S31 is in the support list. You can control the device only after sign in. Please try the following instructions:

1. Open your eWeLink App (iOS / Android) and sign in
2. Add Sonoff S31 to your eWeLink account
3. Sign in again on this addon page
4. Wait a second or click the refresh button
5. Then you can control your devices

: )

**Comment by coolkit-tony** [comment]
Some devices only support cloud mode(need network). Maybe issue #34 could help.
: )
