### ISSUE TITLE
Entities are missing unique ID

### ISSUE THREAD

**Issue by adamjezek98** [CoolKit-Technologies/ha-addon#32]
Devices are missing Uniquie ID, so they cannot be modified in any way in home assistant - name, location, type, etc.  This results in all devices from ewelink shown as one big switch in the dashboard, which cannot be assigned to any room.

Error shown when trying to edit entities in settings:
![image](https://user-images.githubusercontent.com/10603257/135095968-21cb0dc7-08d6-45af-ac63-ecb7b38de123.png)

All devices dispalyed as one in the dashboard:
![image](https://user-images.githubusercontent.com/10603257/135096154-befef6a8-a48d-4c95-99da-074e0cc8b655.png)

**Comment by niezw** [comment]
Yes, haven't found a way to set up unique ID using HA REST API yet.

**Comment by AgentFire** [comment]
MIne switches don't even work, so.
