### ISSUE TITLE
4CHR3 "not supported currently" in configuration.

### ISSUE THREAD

**Issue by JakeMux** [CoolKit-Technologies/ha-addon#34]
Hi, I have a brand new Home Assistant install running, and I have installed your add-on as per your instructions. The add-on finds all my devices on my network, but says "Device not currently supported" under all of them.
They are a mix of 6x 4CHR3 and 3x BasicRFR3, all of which should be supported as stated in your guide. If I login with my Ewelink credentials, they show up and can be controlled, but only through the HA dashboard, not through the iOS Home app.
After a few minutes all devices disappears in the Home app, and your add-on config page comes with an error: "Get-device list failed".

All my Sonoff devices have the latest firmware, and work fine through the Ewelink app, and all of them has LAN control enabled.

**Comment by JakeMux** [comment]
@coolkit-tony Any ideas here buddy? All my Sonoff devices are on the same network as my Home Assistant machine. LAN is enabled on all devices, all running latest firmware. The HA add-on does not find any devices.

**Comment by JakeMux** [comment]
Yeah I also followed the instructions. Tried this on both a PI and on a PC running a clean install of HA. mDNS is turned on on my network, and is working. Weird, this add-on isn't even that old, so you'd think that support would be available.

**Comment by coolkit-tony** [comment]
Hello @JakeMux. 4CHR3 and BasicRFR3 are in the support list. Some devices require you to sign in to use them. Please try the following instructions:

1. Open your eWeLink App (iOS / Android) and sign in
2. Add Sonoff S31 to your eWeLink account
3. Sign in again on this addon page
4. Wait a second or click the refresh button
5. Then you can control your devices

: )

**Comment by JakeMux** [comment]
Thanks. But wouldn't that require me to purchase an S31 to add it?
The S31 is a US smart outlet, won't work in Europe.

**Comment by coolkit-tony** [comment]
Sorry, my fault : (

**Comment by JakeMux** [comment]
The instructions does not mention anything about having to log in, only that this is also an option. It mentions LAN control, which my devices certainly have and use through Homebridge, works even without internet connection.

Besides, the instructions mentions LAN control as something it can do, and if my internet connection goes down, I would lose all control of my Sonoff stuff.

This is what happens:
If I open the add-on, it finds all my Sonoff devices on the network, but lists them as unsupported. If I sign in through the Home Assistant add-on, my devices show up, and I can control them from the add-on page. Then they show up in my iOS Home app, but nothing happens when I tap on them. They show as turned on and off, but the switches themselves does nothing when I tap on them. After a few minutes they disappear from my Home app, and the HA add-on errors with "Failed to get device list", and can't control anything, but still lists the devices.

**Comment by JakeMux** [comment]
Okay so this is the current state:

If I sign into my ewelink account through HA, my devices show now up, and I can add them to my iOS Home app, and I can control everything.

I tried simulating a dropped internet connection by unplugging my modem, and restarted HA. Now I got "Failed to get device list" in the add-on, and all sonoff devices disappeared from the Home app.
 This means that, in the event where my internet connection goes down, I will not be able to control any sonoff device, except through the ewelink app. This also means that all sonoff devices disappear from the Home app, and all automations etc. that has been setup, essentially destroying my HomeKit and control of my house, and I would have to setup everything from scratch again.

That's a really bad thing, Tony. These devices are supposed to be working over LAN too. This makes the add-on completely useless. I can't imagine relying on my wife or kid to know how to setup all this, should I not be there to do it.

**Comment by niezw** [comment]
I think what you need is this.  [sonoff diy mode](http://developers.sonoff.tech/sonoff-diy-mode-api-protocol.html)

ewelink ha add-on need the network to get the data of the device.

**Comment by JakeMux** [comment]
Thanks Gav. I'm using 4CHR3 and BasicR3 (multiple actually) to control everything in my house.

I know that the BasicR3 has DIY, but it would be absolutely awesome if the 4CHR3/PROR3 also had this. I love the DIN mount, and I have 12x 4CHR3 and 6x BasicR3.
