### ISSUE TITLE
addon send false rf brige signals that not actually are received 

### ISSUE THREAD

**Issue by pbvdven** [CoolKit-Technologies/ha-addon#36]
addon send false rf brige signals at random some time every few seconds dan stops for 1 min or so or sometimes for houre and there are not actually received.

![image](https://user-images.githubusercontent.com/39600990/136984504-7339dd02-b52a-4087-b5f2-b37d5169869d.png)
[log.txt](https://github.com/CoolKit-Technologies/ha-addon/files/7331257/log.txt)

**Comment by saliehendricks** [comment]
I am seeing this same problem. 

I have a 3 gang sonoff with the RF bridge. Wifi signals all 100% (they were not at some point).  HA showing false triggers when I enable a simple switch.toggle automation.

![image](https://user-images.githubusercontent.com/1830594/147873715-fe9360a9-8696-47b6-b253-c20f1dceef36.png)

Not sure yet if it is related but HA switches stops triggering the sonoff entities from time to time. Feels like a connection issue between HA and eWlink API (nothing in the logs to confirm this though).

**Comment by niezw** [comment]
Please try to use the latest version, we have done some optimization.

If you still have this problem, please reopen the issue;
If you have other problems, you can create a new issue
