### ISSUE TITLE
Device is not under your account

### ISSUE THREAD

**Issue by TTLucian** [CoolKit-Technologies/ha-addon#37]
It's a sonoff basic1
Sometimes it's ok, but not always. This is a new one:
![Untitled](https://user-images.githubusercontent.com/1855276/137369522-a526f76d-7575-4ed4-b98f-40b43b1b4572.jpg)
Addon version is 1.2.2
HA version is 2021.10.4

**Comment by TTLucian** [comment]
Here's some more:
![Screenshot_2021-10-18-01-32-12-47](https://user-images.githubusercontent.com/1855276/137647348-f8f21710-e1ae-493c-b73d-ccac7492c07a.jpg)

**Comment by TTLucian** [comment]
Of course they are.

**Comment by TTLucian** [comment]
I've just noticed that if I toggle on/off the device with problems and then immediately restart the addon, the error goes away.

**Comment by coolkit-tony** [comment]
Hello, @TTLucian. The strategies for displaying devices are different between ha-addon and eWeLink App. The current version of ha-addon will display devices in the default home, but eWeLink App will display all.

For example:
![baz](https://user-images.githubusercontent.com/87517449/138198610-a35baae3-75af-49de-978e-63ac890f6662.jpg)
I have two homes in this picture.
* eWeLink App - can display devices in office and test
* ha-addon - can display devices in office

Could you please confirm that these "not under your account" devices are in your default home?

**Comment by TTLucian** [comment]
I've deleted and added again the devices which presented this error and they have worked fine for the last weeks. However, today I've noticed another 2 devices with the same error. One of them was previously deleted and added again. Sometimes all it takes for the error to go away is to do a refresh in the addon page or restart the addon but this does not work all the time.

**Comment by comprido** [comment]
I have shared all my devices with my wifes account (can see in her ewelink account all of them), however if I use my wife account in home assistant only some devices will show. 
Please note that if I use my main account (all devices will be visible)

**Comment by GeoffMorg** [comment]
I'm seeing this issue. Four devices in particular, on two Minis, a Basic and a Basic R3. The Basic R3 is for my screens. If I restart the add-on it is fine but if I then manually turn the screen off more often than not it goes into this state. All the time it is OK in the Android app and in Google Home. They are all correctly set up in one Home and I am the only user. I've already been through deleting and re-adding the devices, and re-installing the add-on. It is immensely frustrating.

Addon version is 1.2.3
HA version is 2022.2.3

Is there any log which might help?

**Comment by GeoffMorg** [comment]
I seem to have managed to clear the problem. I suspect something internal got corrupted.

All I did was refresh on the UI page. 

It's odd that I did that AFTER I deleted the add-on and re-added it and still saw the problem.

**Comment by rogerioth** [comment]
Hello, I have the same issue on my setup:
![Capture](https://user-images.githubusercontent.com/9361619/188492968-15be1126-0f8e-4780-aa49-f40c73a5288c.PNG)

From the logs:

`Sep 05 12:03:41 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:41.544Z [ERROR] getDataSync: disabled.json -> 10016412a8 no data
Sep 05 12:03:41 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:41.544Z [ERROR] getDataSync: diy.json ->  no data
Sep 05 12:03:41 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:41.545Z [INFO] Found LAN enhanced plug
Sep 05 12:03:41 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:41.546Z [ERROR] getDataSync: disabled.json -> 10016412a3 no data
Sep 05 12:03:41 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:41.546Z [ERROR] getDataSync: diy.json ->  no data
Sep 05 12:03:41 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:41.547Z [INFO] Found LAN enhanced plug
Sep 05 12:03:41 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:41.548Z [ERROR] getDataSync: diy.json ->  no data
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.329Z [INFO] Found LAN enhanced plug
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.329Z [ERROR] getDataSync: diy.json ->  no data
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.331Z [INFO] Found LAN enhanced plug
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.331Z [ERROR] getDataSync: disabled.json -> 10016412a8 no data
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.332Z [ERROR] getDataSync: diy.json ->  no data
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.333Z [INFO] Found LAN enhanced plug
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.333Z [ERROR] getDataSync: disabled.json -> 10016412fc no data
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.334Z [ERROR] getDataSync: diy.json ->  no data
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.335Z [INFO] Found LAN enhanced plug
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.336Z [ERROR] getDataSync: disabled.json -> 10016412a3 no data
Sep 05 12:03:43 homeassistant b899c1364c8e[1367]: 2022-09-05T17:03:43.336Z [ERROR] getDataSync: diy.json ->  no data
`

**Comment by niezw** [comment]
Please try to use the latest version, we have done some optimization.

If you still have this problem, please reopen the issue;
If you have other problems, you can create a new issue
