### ISSUE TITLE
Some devices shown as not LAN mode

### ISSUE THREAD

**Issue by va4ok** [CoolKit-Technologies/ha-addon#40]
For some reason one of my devices shown as not LAN in HA plugin but in mobile eWeLink app it shows correct. (please see screenshots). So it causes status delay or commands delay.

HA core-2021.10.5 (and earlier)
eWeLink Smart Home plugin version: 1.2.3 (and earlier)

Is it possible to configure plugin to use LAN connection instead of cloud?

![Screenshot 2021-10-19 204416](https://user-images.githubusercontent.com/5189009/137955974-bdb5792b-a4c7-43a8-873f-a1cd27b6ef59.jpg)
![Screenshot_20211019-204258](https://user-images.githubusercontent.com/5189009/137955981-858983bd-b491-495b-94b0-4c755b8552e6.jpg)
![Screenshot_20211019-205618](https://user-images.githubusercontent.com/5189009/137957714-4bc9bb6c-e647-40df-90e3-a5052891d714.jpg)

**Comment by coolkit-tony** [comment]
Hello, @va4ok. Are device "water heater socket" and ha-addon on the same LAN?

**Comment by va4ok** [comment]
Hi, @coolkit-tony  
Yes, they are in the same LAN as well as others devices (please see first screenshot).

**Comment by coolkit-tony** [comment]
Hi, @va4ok. I tested this issue yesterday. This occurs when the ha-addon does not receive some packets sent from the device. Wait a moment or click the refresh button would help.

**Comment by va4ok** [comment]
Yeah service is registered
![image](https://user-images.githubusercontent.com/5189009/139698501-fc29f3b3-7e2a-4597-aed5-550f55a79c55.png)
but nothing changed in HA (last reboot more than 2 days ago)
Looks like a minor bug.

But if it won't be fixed let's close as is.

**Comment by Bloodiss** [comment]
Guys, any upates?
I have same isues with all Sonoff devices (dont working via LAN, only via cloud)

**Comment by niezw** [comment]
Please try to use the latest version, we have done some optimization.

If you still have this problem, please reopen the issue;
If you have other problems, you can create a new issue
