### ISSUE TITLE
DW-2-Wi-fi don't show the change of state on HA

### ISSUE THREAD

**Issue by marcosvbraun** [CoolKit-Technologies/ha-addon#43]
I installed the add-on and all my sonoff devices worked well, except my DW-2-Wi-fi sensor.
Right after I synchronized it (with my Eyelink account) it worked well. However, when I stay some hours without open/close my door, HA can't see the change of state anymore.
But it still works on Ewelink app (it changes the state normally there). So, I think the problem is on the add-on.
Can you help me?

**Comment by niezw** [comment]
It is recommended that you upgrade to the latest version of addon.
If you have any more questions, please reopen this issues. Thank you for your reply.
