### ISSUE TITLE
Cannot read attributes from Sonoff WiFi Bulb B02-B

### ISSUE THREAD

**Issue by Maco65** [CoolKit-Technologies/ha-addon#46]
I have Sonoff WiFi bulb B02-B integrated into HA with this eWeLink Smart Home Add-on.It was easy to setup and basics are working fine.
Now when I want to build some automation (read brightness value and change it) with this bulb I am not able to read brightness attribute.
In Developing tools I can see the entity related to this bulb (it is ` light.10010aaa88`) and when I put the following into templating tool (from Developer tools):
```
Sonoff bulb {{ states.light.10010aaa88 }}
```
I am getting the following message:
```
TemplateSyntaxError: expected token 'end of print statement', got 'aaa88'
```
Other lights have no problems reading attributes.
Is there anything wrong with my setup ?

**Comment by niezw** [comment]
It is recommended that you upgrade to the latest version of addon.
If you have any more questions, please reopen this issues. Thank you for your reply.
