### ISSUE TITLE
Not able to rename entities

### ISSUE THREAD

**Issue by grfernandes54** [CoolKit-Technologies/ha-addon#48]
I cannot rename the entities created at home assistant by this addon

Rename the entities is necessary when you have a large number of devices, specially when use the node red for create the automations. Node red only accept the entities names

**Comment by coolkit-tony** [comment]
Hi, @grfernandes54. Do you mean you can't rename your devices when ha-addon is running?

**Comment by grfernandes54** [comment]
Hello Home assistant have the entity name and the friendly name.
When I rename the device at addon the friendly name at home assistant is
updated buy the entity name keep the same

The problem with the entity name using only the standard name with numbers
is when we try to create some rules at Node Red. Node Red only allow me to
create automations using the entity name, it not use the friendly name
making impossible to create a code when you have multiple devices

Em qui., 2 de dez. de 2021 06:26, coolkit-tony ***@***.***>
escreveu:

**Comment by tefracky** [comment]
Thats a really good question, I have a similar problem and I also want to change the entity_id. How is it possible?

**Comment by danielbrunt57** [comment]
I fail to see the issue with naming.  Just use the entity_id like switch.10012b7d75, switch.10012ef410.  It is not possible to rename the entity_id as that comes from eWeLink and it is the device's Device ID.  Maybe when this add-on matures it will be possible to do that, like with can with other add-ons...

The problem I am having is that even though I pick the numbered entity_id in Node Red, call service switch.turn_on or switch.turn off doesn't work.  Executing switch.turn_on/off inside HA itself works but not from Node Red...

**Comment by danielbrunt57** [comment]
The other older HACS integration [AlexIT/SonoffLAN](https://github.com/AlexxIT/SonoffLAN) works for me...

**Comment by comprido** [comment]
This is linked with the unique_id point, mentioned on https://github.com/CoolKit-Technologies/ha-addon/issues/53

**Comment by niezw** [comment]
The way we add entity is to use the HA Rest API, which does not provide the ability to set unique ID.

https://developers.home-assistant.io/docs/api/rest
