### ISSUE TITLE
Switch.Toggle service isn't working on Ewelink switches even from HA

### ISSUE THREAD

**Issue by peterterbe** [CoolKit-Technologies/ha-addon#52]
If I test my Ewelink switches from the HA Developer tools/Services, they are not working with **switch.toggle**. 
Services **switch.turn_on** and **switch.turn_off** are working however. Other (non-ewelink) switches are working with switch.toggle as well as from the app and from the watch, too.

I was about to use apps on my WearOS watch. Ewelink switches did nothing from the official wearos app (beta) so I had opened [issue1954](https://github.com/home-assistant/android/issues/1954) there and slowly it became clear that it is caused by the addon. It wasn't working from the Home Slide app either (it's an unofficial HA client).

Tested versions:
Ewelink Addon 1.2.3
Home Assistant OS 7.0.rc1
Home Assistant Android client beta-1744-9fd3164-full

**Comment by coolkit-tony** [comment]
Hi, @perriert. The ha-addon doesn't support switch.toggle yet.

**Comment by perriert** [comment]
> Hi, @perriert. The ha-addon doesn't support switch.toggle yet.

Thanks! Are there any plans to support it in the near future?

**Comment by coolkit-tony** [comment]
Hi, @perriert. My current task is to refactor some features that might cause bugs. This may take some time.

**Comment by AlPinkish** [comment]
Hi @perriert , I don't know if you need a workaround for this problem, in any case you can find my simple solution on [HA community](https://community.home-assistant.io/t/ewelink-integration-doesnt-work-with-switch-toggle-bug-workaround/364780)

**Comment by niezw** [comment]
suggest you refer to [this](https://github.com/CoolKit-Technologies/ha-addon/tree/master/eWeLink_Smart_Home) to deal with
