### ISSUE TITLE
Add unique_id

### ISSUE THREAD

**Issue by Antoni-Czaplicki** [CoolKit-Technologies/ha-addon#53]
@coolkit-tony do you have any plans for adding mac as unique_id to devices?

**Comment by coolkit-tony** [comment]
Hello, @Antoni-Czaplicki. Is there any reason to do this?

**Comment by Antoni-Czaplicki** [comment]
Yes, adding it would allow us to configure the device (change name or entity-id) with ui. https://developers.home-assistant.io/docs/entity_registry_index#unique-id

**Comment by niezw** [comment]
Has been supported on the latest version

**Comment by niezw** [comment]
The way we add entity is to use the HA Rest API, which does not provide the ability to set unique ID.

https://developers.home-assistant.io/docs/api/rest
