### ISSUE TITLE
Device is on my mobile app and HA eWeLink tab, but not avalable in Lovelace

### ISSUE THREAD

**Issue by Zodiac-69** [CoolKit-Technologies/ha-addon#56]
I have one (1) device - Pool Pump - that is on my mobile app (eWeLink) and it is shown in the EweLink Smart Home tab in HA, but on the Lovelace tab, it  is shown as "Entity not available: 10007908a0.
I do also not see it listed under with the other SonOff devices under the "Development Tools" tab in HA.

Any idea where i can see why it is not shown?

![image](https://user-images.githubusercontent.com/2076401/146631426-6b9bcf55-36ab-48a1-a15f-4cade237587e.png)
![image](https://user-images.githubusercontent.com/2076401/146631433-70be1919-1410-464b-bc77-9e53ee95c0f6.png)

**Comment by niezw** [comment]
Temp2 and Temp1 is offline.

It is recommended that you upgrade to the latest version of addon.
If you have any more questions, please reopen this issues. Thank you for your reply.
