### ISSUE TITLE
Unable to find referenced entities switch.*

### ISSUE THREAD

**Issue by pniewiadowski** [CoolKit-Technologies/ha-addon#63]
Hi there,

I am using 1.2.3 version and have added Sonof Mini.
When I try to switch it on/off from HA, this is what I got in logs and the switch doesn't react.
Please help

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:129
First occurred: 9:06:44 PM (3 occurrences)
Last logged: 9:07:04 PM

Unable to find referenced entities switch.xxxxxxxxxxx
```

**Comment by niezw** [comment]
suggest you try [this](https://github.com/CoolKit-Technologies/ha-addon/tree/master/eWeLink_Smart_Home)

It is recommended that you upgrade to the latest version of addon.
If you have any more questions, please reopen this issues. Thank you for your reply.
