### ISSUE TITLE
Consumption on Energy panel

### ISSUE THREAD

**Issue by miklosandras** [CoolKit-Technologies/ha-addon#64]
Dear Support,

May I ask you that  will be available sonoff consumption (I have 3 POW R2) on integrated energy panel in HA?

Thank you in advance.

**Comment by Chatocampeon** [comment]
I have the sane cuestion. I have a power R2 and the only entity available is the switch. We need Power and Voltage entites.

**Comment by niezw** [comment]
Please use the latest version, we have made some updates

If you still have this problem, please reopen the issue.
If there are other problems, please create a new issue.
