### ISSUE TITLE
Unable to enter Long Access Token in Addon config

### ISSUE THREAD

**Issue by Gotcha-1980** [CoolKit-Technologies/ha-addon#65]
I have installed the addon, and created a Long Access Token for it, but when I go to the 'Configuration' tab, I do not have the options section displayed, and there is no fields available for the Long Access Token. I access Home Assistant via Duckdns. Any thoughts, as currently I have to log in several times a day to keep the connection alive. Thanks.

**Comment by five2seven** [comment]
Any update on this? Just set it up today for the first time and have the same issue.

**Comment by alberfito** [comment]
Same problem

**Comment by niezw** [comment]
The latest version no longer requires the use of long-term access tokens

If you still have this problem, please reopen this issue.
If there are other problems, please create a new issue.
