### ISSUE TITLE
Sonoff USB Micro freezes in ha-addon

### ISSUE THREAD

**Issue by stanislav-brabec** [CoolKit-Technologies/ha-addon#67]
I have two Sonoff USB Micro and more other Sonoff devices.

About once per week, all Sonoff USB Micro devices stop to respond in Home Assistant. Clicking to their entities, the status changes for a second and then returns back. In the Addon UI, the device does not respond. All other devices (not Sonoff USB Micro) continue to work as expected. Sonoff USB Micro devices continue to work normally in the EWeLink Smart Home Android application.

Restart of the addon fixes the problem, but it re-appears again in several days.

**Comment by niezw** [comment]
Please use the latest version, we have made some updates

If you still have this problem, please reopen the issue.
If there are other problems, please create a new issue.
