### ISSUE TITLE
ewelink add-on broken since update

### ISSUE THREAD

**Issue by gfn256** [CoolKit-Technologies/ha-addon#72]
Since updating to supervisor-2022.03.3,this ewelink official addon has broken. It produces WebSocket errors in supervisor log.

The only workaround is to refresh from the ewelink webui in home assistant.

Maybe there is some way to do this automatically?

Please someone help!

**Comment by ZachPL** [comment]
I'm also having an issue where my plug turns on fine from homeassistant, but when I go to turn it off it does nothing there is this error in the logs

Logger: homeassistant.helpers.service
Source: helpers/service.py:130
First occurred: 5:00:00 PM (8 occurrences)
Last logged: 10:12:00 PM

Unable to find referenced entities switch.100153c6a1

**Comment by ZachPL** [comment]
I'm running on homeOS on a synology nas VM, but this randomly started working again a few days ago, although this error is still showing in the logs.

**Comment by gfn256** [comment]
> Hello, @gfn256 @ZachPL. Are you running Home Assistant on Respberry Pi?

Raspberry Pi

**Comment by coolkit-tony** [comment]
Thanks for your feedback. We will try to reproduce these issues on Pi and VM. I'm sorry for the poor experience.

**Comment by iamandymcinnes** [comment]
I'm also seeing this happening all the time. I go to turn something on or off and it doesn't work. I then check the addon ui and a number of my sonoff devices will say something like "device not associated with account" then if I press the refresh button in the addon ui it reloads my devices.

**Comment by niezw** [comment]
Please use the latest version, we have made some updates

If you still have this problem, please reopen the issue.
If there are other problems, please create a new issue.
