### ISSUE TITLE
Set "Integration" for devices/entities to "eWeLink" f.e.

### ISSUE THREAD

**Issue by Masterz69** [CoolKit-Technologies/ha-addon#75]
Add-on related entities should have "Integration" set to add-on name.

This is actually current practice, used widely.
Setting Integration=Sensor for sensor and so on is wrong idea.

With best wishes.

**Comment by coolkit-tony** [comment]
Hello, @Masterz69. Thanks for your feedback. Do you mean the entity_id should be changed?

**Comment by niezw** [comment]
Thank you for your reply. Could you tell me more about it?

**Comment by niezw** [comment]
Can you tell us in more detail to help us better understand what you mean? thank you for your reply! @Masterz69

**Comment by Masterz69** [comment]
![image](https://user-images.githubusercontent.com/15225823/188468497-0d56b08d-2cf5-444d-b2c3-710ebf0781f4.png)

Will on example. You can see on screenshot devices & entities created by same Integration.
All of them have property 'Integration' set to Integration name.
Actually this common practice in HA.
As far I see.

**Comment by niezw** [comment]
> 


We agree with you.

But our AddOn doesn't create entity in the same way as integration. We use [REST API](https://developers.home-assistant.io/docs/api/rest).

integration name as "Switch", is the default of HA .We can't make any changes.

**Comment by niezw** [comment]
If you have any other questions, please create new issues. Thank you for your reply.
