### ISSUE TITLE
Confguration Token is does not exists after install the addon

### ISSUE THREAD

**Issue by DavidFFerreira** [CoolKit-Technologies/ha-addon#76]
Confguration Token is does not exists after install the addon

![image](https://user-images.githubusercontent.com/32928749/160157402-83d5eba5-59b2-4ffa-bcad-c2dbab6307d8.png)
![image](https://user-images.githubusercontent.com/32928749/160157184-f75813d5-5493-43c2-b79d-3c3f183bc995.png)
![image](https://user-images.githubusercontent.com/32928749/160157837-2289b8b3-dcca-4dff-985f-d1544cf9e65f.png)

**Comment by DavidFFerreira** [comment]
@niezw 
@ZJia1231 
@coolkit-tony 

Can u help us?

**Comment by coolkit-tony** [comment]
Hello, @DavidFFerreira. The tutorial was out of dated. The old version addon needs it (current version don't). We will update the tutorial soon. Thanks for your feedback.

**Comment by DavidFFerreira** [comment]
@coolkit-tony  can u give me some advice to make it work? because its still dont work at all

**Comment by coolkit-tony** [comment]
Hi, @DavidFFerreira. Can you login in the web ui?

**Comment by DavidFFerreira** [comment]
@coolkit-tony yes I can, but still got error when try to get devices from HA, btw no one can get tthis to work

**Comment by alberfito** [comment]
> 
I have the same issue. Cannot get devices from HA

**Comment by DavidFFerreira** [comment]
@coolkit-tony any help to make my devices showing in ewelink app?!

**Comment by coolkit-tony** [comment]
Hello @alberfito, The WebSocket connection to the Home Assistant may have been disconnected. Restart this addon may help. Sorry for the poor experience.

**Comment by coolkit-tony** [comment]
Hello @DavidFFerreira, you can download eWeLink app from App Store (iOS) or Google Play (Android).

**Comment by DavidFFerreira** [comment]
@coolkit-tony yes i have it for android
@coolkit-tony if you go to home assistant discord or channels, you will see that no one can use it. You have https://Homeassistant.local all over the code, of course it will not work!

**Comment by niezw** [comment]
Please update to the latest version （v1.3.1） and try again ~
