### ISSUE TITLE
[BUG] Get device list failed / couldn't get HA device

### ISSUE THREAD

**Issue by tianzhuang55** [CoolKit-Technologies/ha-addon#83]
ha-addon version: 1.2.6
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 7.6

Successfully login ewelink account and all the ewelink devices are listed, but not able to get HA device list.

**Comment by devpumk** [comment]
Same here...any news or solutions?

**Comment by carfnann** [comment]
have you been able to sync HA Devices? I'm still having the message "Get device list failed"...
