### ISSUE TITLE
The command '/bin/sh -c apt-get update && apt-get install -y python build-essential' returned a non-zero code: 100

### ISSUE THREAD

**Issue by mickael00x** [CoolKit-Technologies/ha-addon#84]
The command '/bin/sh -c apt-get update && apt-get install -y python build-essential' returned a non-zero code: 100

**Comment by niezw** [comment]
I don't quite understand your question. Can you give me a more detailed description?

It looks a bit like a system error report.

**Comment by niezw** [comment]
We found that when the network is bad, it will appear when you install addon. 
Reinstall or try using a network agent.

If you have any more questions, please create a new issue
