### ISSUE TITLE
docker registry timeout

### ISSUE THREAD

**Issue by GaetanoCarlucci** [CoolKit-Technologies/ha-addon#92]
I have HA installed on raspberry pi 4.

When I click on install i get the following error:

`Get "https://registry-1.docker.io/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by niezw** [comment]
It seems to be a problem of accessing docker.io. There may be network fluctuations. You can try again many times.

If you have any more questions, please reopen this issues. Thank you for your reply.
