### ISSUE TITLE
Suggest add tip to wiki about rtefreshing page

### ISSUE THREAD

**Issue by otzen** [CoolKit-Technologies/ha-addon#93]
Hi

I followed the steps in the wiki on [how to add ewlink app to homeassiustant](https://appcms-src.coolkit.cn/uncategorized/9213.html]).

## Problem
after adding the repository no eWlink app showed up in the overview, even selcting serach and typing ew gave no result.
I googled a lot, and wasted a lot of time until i found that all i needed to do was to hit [F5] refresh page....

## Suggested solution
I suggest you add a hint on the wiki
from:
```
After closing the modal box, you can see the newly added eWeLink add-on on Add-on Store page.

Click the eWeLink Smart Home card
```
To:
```
After closing the modal box, you can see the newly added eWeLink add-on on Add-on Store page, (if it doews not show try refreshing the page by hitting F5).

Click the eWeLink Smart Home card
```

**Comment by niezw** [comment]
Thanks for your reply, can you provide some screenshots? The installation steps for this  [wiki](https://appcms-src.coolkit.cn/uncategorized/9213.html)

If there are still problems, please reopen this issues~
