### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by EmileSpecs** [CoolKit-Technologies/ha-addon#94]
Hi

Is there any ETA on supporting SPM Main and SPM Relay devices?

Thanks!

**Comment by rdgilmour** [comment]
I am also waiting for this. Happy to help troubleshoot.

**Comment by niezw** [comment]
It is not supported yet, and we will arrange the support plan according to the number of devices in the future version.
If you have any more questions, please reopen this issues. Thank you for your reply.
