### ISSUE TITLE
Can not install eWeLink Home Assistant Add-on

### ISSUE THREAD

**Issue by lecrams** [CoolKit-Technologies/ha-addon#96]
When I try to add this repro to hassio I get:
![image](https://user-images.githubusercontent.com/74721082/182317574-faacc137-7003-4244-ac57-f9b724ac6624.png)

What is wrong?

**Comment by unosakk** [comment]
i went to the URL and then copy-d the URL from browser view. Then it was Okey somehow.

**Comment by leisefuxX** [comment]
i had the same problem. pressed F5 and it was okay 👍

**Comment by niezw** [comment]
Look like network fluctuations, this URL is the github address, if there are still problems, please open this issues~

**Comment by xurizaemon** [comment]
Looks like there may have been whitespace before/after the URL?
